import { html as htmlBeautify } from "js-beautify";
import { qs, delegate, escapeHtml } from "../../scripts/dom.js";
import { EVENTS, on } from "../../scripts/events.js";
import template from "./code_snippet.html?raw";

function convertRgbToHex(markup) {
  return markup.replace(
    /rgba?\((\d+),\s?(\d+),\s?(\d+)\)/gim,
    (match, r, g, b) =>
      "#" +
      [r, g, b]
        .map((value) => parseInt(value, 10).toString(16).padStart(2, "0"))
        .join(""),
  );
}

class CodeSnippetElement extends HTMLElement {
  connectedCallback() {
    this.innerHTML = template;

    qs(".es-code-snippet__hide-button", this).addEventListener("click", () => {
      document.body.classList.remove("es-code-toggle--visible");
    });

    delegate(this, "click", ".es-code-snippet__copy-button", (event, button) => {
      event.preventDefault();
      this.#copyToClipboard(button);
    });

    on(EVENTS.showCodeSnippet, () => this.#updateContent());
  }

  #setLoading(isLoading) {
    qs(".es-code-snippet", this).classList.toggle(
      "es-code-snippet--loading",
      isLoading,
    );
  }

  #updateContent() {
    qs(".es-code-snippet__persistent-url", this).value = window.location.href;
    this.#setLoading(true);

    // Yield once so the loading state paints before the synchronous beautify.
    setTimeout(() => {
      const markup = convertRgbToHex(
        qs("es-contrast-grid").getPortableMarkup(),
      );
      const formatted = htmlBeautify(markup, { preserve_newlines: false });

      qs(".es-code-snippet code", this).innerHTML =
        "&lt;!-- Contrast Grid generated by contrast-grid.eightshapes.com --&gt;\n" +
        "&lt;!-- Editable link: " +
        escapeHtml(window.location.href) +
        " --&gt;\n" +
        escapeHtml(formatted);

      this.#setLoading(false);
    }, 50);
  }

  async #copyToClipboard(button) {
    const target = qs(button.dataset.clipboardTarget);
    const response = qs(".es-code-snippet__copy-response", button);

    button.classList.remove("es-code-snippet__copy-button--clicked");
    void button.offsetHeight;

    try {
      await navigator.clipboard.writeText(target.value ?? target.textContent);
      response.textContent = "Copied!";
    } catch {
      response.textContent = "Press Ctrl + C to copy";
    }

    button.classList.add("es-code-snippet__copy-button--clicked");
  }
}

customElements.define("es-code-snippet", CodeSnippetElement);
